name: "Download nwserver"
inputs:
  preview:
    description: "Preview version"
    required: true
    default: "false"
  steam_username:
    description: "Steam username"
    required: true
  steam_password:
    description: "Steam password"
    required: true
  nwn_app_id:
    description: "NWN App ID"
    required: true
    default: "704450"
  nwn_win_bin_depot_id:
    description: "NWN Win Bin Depot ID"
    required: true
    default: "704452"
  nwn_linux_bin_depot_id:
    description: "NWN Linux Bin Depot ID"
    required: true
    default: "704454"
  nwn_content_depot_id:
    description: "NWN Content Depot ID"
    required: true
    default: "704451"
outputs:
  version:
    description: "Version"
    value: ${{ steps.nwn.outputs.version }}
  major:
    description: "Major version"
    value: ${{ steps.nwn.outputs.major }}
  minor:
    description: "Minor version"
    value: ${{ steps.nwn.outputs.minor }}
  patch:
    description: "Patch version"
    value: ${{ steps.nwn.outputs.patch }}
runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v3"
    - name: Clone SteamRE/DepotDownloader
      shell: bash
      run: |
        git clone https://github.com/SteamRE/DepotDownloader.git
    - name: Download nwnee files
      shell: bash
      run: |
        cd DepotDownloader/DepotDownloader
        if [ "${{ inputs.preview }}" = "true" ]; then
          EXTRA_ARGS="-betapassword previewpreview -beta preview"
        else
          EXTRA_ARGS=""
        fi
        dotnet run -app ${{ inputs.nwn_app_id }} -depot ${{ inputs.nwn_win_bin_depot_id }} -username ${{ inputs.steam_username }} -password ${{ inputs.steam_password }} $EXTRA_ARGS
        dotnet run -app ${{ inputs.nwn_app_id }} -depot ${{ inputs.nwn_linux_bin_depot_id }} -username ${{ inputs.steam_username }} -password ${{ inputs.steam_password }} $EXTRA_ARGS
        dotnet run -app ${{ inputs.nwn_app_id }} -depot ${{ inputs.nwn_content_depot_id }} -username ${{ inputs.steam_username }} -password ${{ inputs.steam_password }} $EXTRA_ARGS
    - name: Install semver
      shell: bash
      run: |
        sudo apt install unzip pev
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
    - name: Parse nwnee files
      shell: bash
      id: nwn
      run: |
        cd ${{ github.workspace }}/DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_win_bin_depot_id }}/*/bin/win32/
        VERSION=$(peres -v nwserver.exe -f csv | grep -v DEBUG | cut -d'.' -f2- | sed -n 2p)
        MAJOR=$(semver get major $VERSION)
        MINOR=$(semver get minor $VERSION)
        PATCH=$(semver get patch $VERSION)
        echo version=$VERSION >> $GITHUB_OUTPUT
        echo major=$MAJOR >> $GITHUB_OUTPUT
        echo minor=$MINOR >> $GITHUB_OUTPUT
        echo patch=$PATCH >> $GITHUB_OUTPUT
    - name: Install Neverwinter.nim
      shell: bash
      run: |
        wget -O nwn-nim.zip https://github.com/niv/neverwinter.nim/releases/download/1.7.1/neverwinter.linux.amd64.zip
        unzip -j nwn-nim.zip nwn_resman_pkg -d /usr/local/bin/
        chmod +x /usr/local/bin/nwn_resman_pkg
        echo /usr/local/bin/ >> $GITHUB_PATH
    - name: Package nwserver files
      shell: bash
      env:
        NWN_ROOT: ./
      run: |
        mkdir -p nwserver/docker/lang/en/data docker/data/bin/linux-amd64 docker/data/bin/linux-arm64 docker/data/data/mod/
        cd DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_content_depot_id }}/*/
        nwn_resman_pkg --userdirectory . -d ${{ github.workspace }}/docker/data/data
    - name: Assemble other nwserver files
      shell: bash
      run: |
        ls -al .
        ls -al DepotDownloader/
        ls -al DepotDownloader/DepotDownloader/
        ls -al DepotDownloader/DepotDownloader/depots/
        ls -al DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_win_bin_depot_id }}/
        ls -al DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_win_bin_depot_id }}/*/
        ls -al DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_win_bin_depot_id }}/*/data

        ls DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_win_bin_depot_id }}/*/
        cd DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_win_bin_depot_id }}/*/data/bin/win32/
        cp nwserver.exe ${{ github.workspace }}/docker/bin/win32/nwserver.exe

        ls DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_linux_bin_depot_id }}/*/
        cd ${{ github.workspace }}/DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_linux_bin_depot_id }}/*/data/bin/linux-x86/
        cp nwserver ${{ github.workspace }}/docker/bin/linux-x86/nwserver
        cd ${{ github.workspace }}/DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_linux_bin_depot_id }}/*/data/bin/linux-arm64/
        cp nwserver ${{ github.workspace }}/docker/bin/linux-arm64/nwserver

        ls DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_content_depot_id }}/*/
        cd ${{ github.workspace }}/DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_content_depot_id }}/*/data/
        cp cacert.pem ${{ github.workspace }}/docker/data/data/cacert.pem
        cd ${{ github.workspace }}/DepotDownloader/DepotDownloader/depots/${{ inputs.nwn_content_depot_id }}/*/data/lang/en/data/
        cp dialog.tlk ${{ github.workspace }}/docker/lang/en/data/dialog.tlk

        cp -r scripts/. ${{ github.workspace }}/docker/
        cp -r DockerDemo.mod ${{ github.workspace }}/docker/
