name: "Parse nwserver"
outputs:
  version:
    description: "Version"
    value: ${{ steps.nwn.outputs.version }}
  major:
    description: "Major version"
    value: ${{ steps.nwn.outputs.major }}
  minor:
    description: "Minor version"
    value: ${{ steps.nwn.outputs.minor }}
  patch:
    description: "Patch version"
    value: ${{ steps.nwn.outputs.patch }}
runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt install unzip pev
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
    - name: Parse nwnee files
      id: nwn
      shell: bash
      env:
        WIN_BIN_DEPOT_ID: 704452
      run: |
        cd ${{ github.workspace }}/DepotDownloader/DepotDownloader/depots/$WIN_BIN_DEPOT_ID/*/bin/win32/
        echo version=$(peres -v nwserver.exe -f csv | grep -v DEBUG | cut -d'.' -f2- | sed -n 2p) >> $GITHUB_OUTPUT
        echo major=$(semver get major $(peres -v nwserver.exe -f csv | grep -v DEBUG | cut -d'.' -f2- | sed -n 2p)) >> $GITHUB_OUTPUT
        echo minor=$(semver get minor $(peres -v nwserver.exe -f csv | grep -v DEBUG | cut -d'.' -f2- | sed -n 2p)) >> $GITHUB_OUTPUT
        echo patch=$(semver get patch $(peres -v nwserver.exe -f csv | grep -v DEBUG | cut -d'.' -f2- | sed -n 2p)) >> $GITHUB_OUTPUT
