name: "Parse nwserver"
inputs:
  path:
    description: "Path"
    required: true
    default: ${{ github.workspace }}/nwserver
    type: string

runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v3"
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt install unzip
        wget -O nwn-nim.zip https://github.com/niv/neverwinter.nim/releases/download/1.7.1/neverwinter.linux.amd64.zip
        unzip -j nwn-nim.zip nwn_resman_pkg -d /usr/local/bin/
        chmod +x /usr/local/bin/nwn_resman_pkg
        echo /usr/local/bin/ >> $GITHUB_PATH
        rm nwn-nim.zip
    - name: Package nwnee files
      shell: bash
      env:
        NWN_ROOT: ./
        APP_ID: 704450
        BUILD_ID: 11253735
        WIN_BIN_DEPOT_ID: 704452
        LINUX_BIN_DEPOT_ID: 704454
        CONTENT_DEPOT_ID: 704451
      run: |
        ls -la $GITHUB_WORKSPACE
        ls -la

        cd DepotDownloader/DepotDownloader/depots/$LINUX_BIN_DEPOT_ID/*/bin/linux-x86/
        cp nwserver-linux $GITHUB_WORKSPACE/packaged/data/bin/linux-amd64/nwserver
        cd $GITHUB_WORKSPACE

        cd DepotDownloader/DepotDownloader/depots/$WIN_BIN_DEPOT_ID/*/bin/win32/
        cp nwserver.exe $GITHUB_WORKSPACE/packaged/nwserver.exe
        cd $GITHUB_WORKSPACE

        cd DepotDownloader/DepotDownloader/depots/$LINUX_BIN_DEPOT_ID/*/bin/linux-arm64/
        cp nwserver-linux $GITHUB_WORKSPACE/packaged/data/bin/linux-arm64/nwserver
        cd $GITHUB_WORKSPACE

        cd DepotDownloader/DepotDownloader/depots/$CONTENT_DEPOT_ID/*/data/
        cp cacert.pem $GITHUB_WORKSPACE/packaged/data/data/cacert.pem
        cd $GITHUB_WORKSPACE

        cd DepotDownloader/DepotDownloader/depots/$CONTENT_DEPOT_ID/*/data/
        cp dialog.tlk $GITHUB_WORKSPACE/packaged/data/data/dialog.tlk
        cd $GITHUB_WORKSPACE

        cp -r scripts/. $GITHUB_WORKSPACE/packaged/
        cp -r DockerDemo.mod $GITHUB_WORKSPACE/packaged/

        cd depots/$CONTENT_DEPOT_ID/*/
        nwn_resman_pkg --userdirectory . -d $GITHUB_WORKSPACE/packaged/data/data