name: "Parse nwserver"
inputs:
  path:
    description: "Path"
    required: true
    default: ${{ github.workspace }}/nwserver
    type: string
env:
  NWN_ROOT: ${{ inputs.path }}
runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v3"
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt install unzip
        wget -O nwn-nim.zip https://github.com/niv/neverwinter.nim/releases/download/1.7.1/neverwinter.linux.amd64.zip
        unzip -j nwn-nim.zip nwn_resman_pkg -d /usr/local/bin/
        chmod +x /usr/local/bin/nwn_resman_pkg
        echo /usr/local/bin/ >> $GITHUB_PATH
    - name: Package nwnee files
      shell: bash
      env:
          CONTENT_DEPOT_ID: 704451
      run: |
        cd depots/$CONTENT_DEPOT_ID/*/
        nwn_resman_pkg --userdirectory . -d ${{ inputs.GITHUB_WORKSPACE }}/data/data