name: "Download nwserver"
inputs:
  preview:
    description: "Preview version"
    required: true
    type: boolean
    default: false
  steam_username:
    description: "Steam username"
    required: true
    type: string
  steam_password:
    description: "Steam password"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v3"
    - name: Clone SteamRE/DepotDownloader
      shell: bash
      run: |
        git clone https://github.com/SteamRE/DepotDownloader.git
    - name: Download nwnee files
      shell: bash
      env:
        APP_ID: 704450
        WIN_BIN_DEPOT_ID: 704452
        LINUX_BIN_DEPOT_ID: 704454
        CONTENT_DEPOT_ID: 704451
      run: |
        mkdir -p nwserver/lang/en/data nwserver/data/bin/linux-amd64 nwserver/data/bin/linux-arm64 wserver/data/data/mod/
        cd DepotDownloader/DepotDownloader
        if [ "${{ inputs.preview }}" = "true" ]; then
          EXTRA_ARGS="-betapassword previewpreview -beta preview"
        else
          EXTRA_ARGS=""
        fi
        dotnet run -app $APP_ID -depot $WIN_BIN_DEPOT_ID -username ${{ inputs.steam_username }} -password ${{ inputs.steam_password }} $EXTRA_ARGS
        dotnet run -app $APP_ID -depot $LINUX_BIN_DEPOT_ID -username ${{ inputs.steam_username }} -password ${{ inputs.steam_password }} $EXTRA_ARGS
        dotnet run -app $APP_ID -depot $CONTENT_DEPOT_ID -username ${{ inputs.steam_username }} -password ${{ inputs.steam_password }} $EXTRA_ARGS

        cd ${{ github.workspace }}
        ls -la .
