on:
  pull_request:
jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [preview, release]
    steps:
      - uses: actions/checkout@v4
      - name: NWNEE
        id: nwn
        uses: ./.github/actions/nwserver/
        with:
          preview: ${{ matrix.channel == 'preview' }}
          steam_username: ${{ secrets.STEAM_USER }}
          steam_password: ${{ secrets.STEAM_PASS }}
