on:
  pull_request:
jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [preview, release]
    steps:
      - uses: actions/checkout@v4
      - name: NWNEE
        id: download
        uses: ./.github/actions/nwserver/
        with:
          preview: ${{ matrix.channel == 'preview' }}
          steam_username: ${{ secrets.STEAM_USER }}
          steam_password: ${{ secrets.STEAM_PASS }}
      - name: Debug
        run: |
          ls -la docker/
          echo ${{ steps.download.outputs.version }}
          echo ${{ steps.download.outputs.major }}
          echo ${{ steps.download.outputs.minor }}
          echo ${{ steps.download.outputs.patch }}

      #- name: Parse nwnee
      #  id: parse
      #  uses: ./.actions/nwserver/parse/
      #- name: Package nwnee
      #  id: package
      #  uses: ./.actions/nwserver/package/

