on:
  pull_request:
jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [preview, release]
    steps:
      - uses: actions/checkout@v4
      - name: Download nwnee
        id: download
        uses: ./.actions/nwserver/download/
        with:
          preview: ${{ matrix.channel == 'preview' }}
          steam_username: ${{ secrets.STEAM_USER }}
          steam_password: ${{ secrets.STEAM_PASS }}
          output_path: ${{ github.workspace }}
      - name: Parse nwnee
        id: parse
        uses: ./.actions/nwserver/parse/
      - name: Package nwnee
        id: package
        uses: ./.actions/nwserver/package/

