on:
  pull_request:
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: version
        id: version
        uses: ./.github/actions/version/
      - run: |
          echo "stable: ${{ steps.version.outputs.stable }}"
          echo "development: ${{ steps.version.outputs.development }}"
          echo "preview": ${{ steps.version.outputs.preview }}
          echo "json": ${{ steps.version.outputs.json }}

      #- name: NWNEE
      #  id: nwn
      #  uses: ./.github/actions/nwserver/
      #  with:
      #    steam_username: ${{ secrets.STEAM_USER }}
      #    steam_password: ${{ secrets.STEAM_PASS }}
