on:
  pull_request:
jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [release, preview]
    steps:
      - uses: actions/checkout@v4
      - name: Download nwnee
        uses: ./.actions/nwserver/download/
        with:
          preview:        ${{ matrix.channel == 'preview' }}
          steam_username: ${{ secrets.STEAM_USER }}
          steam_password: ${{ secrets.STEAM_PASS }}
          output_path:    ${{ github.workspace }}


