on:
  pull_request:
jobs:
  build_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [preview, release]
    steps:
      - uses: actions/checkout@v4
      - name: NWNEE
        id: download
        uses: ./.github/actions/nwserver/
        with:
          preview: ${{ matrix.channel == 'preview' }}
          steam_username: ${{ secrets.STEAM_USER }}
          steam_password: ${{ secrets.STEAM_PASS }}
      - name: Debug
        run: |
          ls -R docker/
          echo ${{ steps.download.outputs.version }}
          echo ${{ steps.download.outputs.major }}
          echo ${{ steps.download.outputs.minor }}
          echo ${{ steps.download.outputs.patch }}
      - name: Bookworm docker image
        uses: docker/build-push-action@v3
        with:
          context: docker
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: false
          build-args: |
            DEBIAN_VERSION=bookworm-slim
            NWN_IMAGE_BUILD_DATE=${{ steps.nwn.outputs.now }}
            NWN_VERSION=${{ steps.nwn.outputs.version }}
          labels: |
            org.opencontainers.image.source=https://github.com/urothis/nwserver
            com.nwn.revision=${{ steps.nwn.outputs.version }}
            com.nwn.version=${{ steps.nwn.outputs.version }}
            com.nwn.description="docker image for running a Neverwinter Nights 1 server on Linux"
          tags: |
            urothis/nwserver:${{ steps.nwn.outputs.version }}-bookworm
            urothis/nwserver:${{ steps.nwn.outputs.major }}.${{ steps.nwn.outputs.minor }}-bookworm
            urothis/nwserver:${{ steps.nwn.outputs.major }}-bookworm
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.version }}-bookworm
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.major }}.${{ steps.nwn.outputs.minor }}-bookworm
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.major }}-bookworm
      - name: Bullseye docker image
        uses: docker/build-push-action@v3
        with:
          context: docker
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: false
          build-args: |
            DEBIAN_VERSION=bullseye-slim
            NWN_IMAGE_BUILD_DATE=${{ steps.nwn.outputs.now }}
            NWN_VERSION=${{ steps.nwn.outputs.version }}
          labels: |
            org.opencontainers.image.source=https://github.com/urothis/nwserver
            com.nwn.revision=${{ steps.nwn.outputs.version }}
            com.nwn.version=${{ steps.nwn.outputs.version }}
            com.nwn.description="docker image for running a Neverwinter Nights 1 server on Linux"
          tags: |
            urothis/nwserver:${{ steps.nwn.outputs.version }}-bullseye
            urothis/nwserver:${{ steps.nwn.outputs.major }}.${{ steps.nwn.outputs.minor }}-bullseye
            urothis/nwserver:${{ steps.nwn.outputs.major }}-bullseye
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.version }}-bullseye
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.major }}.${{ steps.nwn.outputs.minor }}-bullseye
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.major }}-bullseye
      - name: Buster docker image
        uses: docker/build-push-action@v3
        with:
          context: docker
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: false
          build-args: |
            DEBIAN_VERSION=buster-slim
            NWN_IMAGE_BUILD_DATE=${{ steps.nwn.outputs.now }}
            NWN_VERSION=${{ steps.nwn.outputs.version }}
          labels: |
            org.opencontainers.image.source=https://github.com/urothis/nwserver
            com.nwn.revision=${{ steps.nwn.outputs.version }}
            com.nwn.version=${{ steps.nwn.outputs.version }}
            com.nwn.description="docker image for running a Neverwinter Nights 1 server on Linux"
          tags: |
            urothis/nwserver:${{ steps.nwn.outputs.version }}
            urothis/nwserver:${{ steps.nwn.outputs.major }}.${{ steps.nwn.outputs.minor }}
            urothis/nwserver:${{ steps.nwn.outputs.major }}
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.version }}
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.major }}.${{ steps.nwn.outputs.minor }}
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.major }}
            urothis/nwserver:${{ steps.nwn.outputs.version }}-buster
            urothis/nwserver:${{ steps.nwn.outputs.major }}.${{ steps.nwn.outputs.minor }}-buster
            urothis/nwserver:${{ steps.nwn.outputs.major }}-buster
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.version }}-buster
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.major }}.${{ steps.nwn.outputs.minor }}-buster
            ghcr.io/${{ github.repository }}:${{ steps.nwn.outputs.major }}-buster

      #- name: Parse nwnee
      #  id: parse
      #  uses: ./.actions/nwserver/parse/
      #- name: Package nwnee
      #  id: package
      #  uses: ./.actions/nwserver/package/

